name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Configures Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Clones the code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Tests
      run: go test -v -cover ./...

    - name: Benchmark
      run: go test -v -benchmem -bench . -run ^$ ./...
